package:
  name: fahmunge-dev
  version: 0.0.0

source:
  path: ../..

build:
  preserve_egg_dir: True
  number: 0
  entry_points:
    - munge-fah-data = fahmunge.cli:main

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - numpy
    - pandas
    - pytables
    - natsort
    - mdtraj

test:
  requires:
    - nose
    - nose-timer
    - fahmunge-dev
  imports:
    - fahmunge
  commands:
    - nosetests fahmunge --nocapture --verbosity=2 --with-doctest --with-timer
    - munge-fah-data --help
    - munge-fah-data --version
    # Get some test data
    - git clone https://github.com/choderalab/fahmunge-testdata.git
    - cd fahmunge-testdata
    # Test parallel
    - echo "Testing parallel processing"
    - rm -rf munged
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --validate --nprocesses 2 --xml compress
    # Test restart after unpacking (shouldn't actually do anything)
    - echo "Testing additional processing iterations"
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --validate --nprocesses 2  --xml compress
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1
    - munge-fah-data --projects projects.csv --outpath munged --maxits 2 --sleeptime 1
    # TODO: Test to make sure expected output is found
    - ls -ltr munged/11507
    - ls -ltr munged/11431
    - ls -ltr PROJ11507/RUN?/CLONE?/results?/*.xml.gz
    # Remove unpacked files
    - rm -rf PROJ11507/RUN?/CLONE?/results?
    - rm -rf PROJ11419/RUN?/CLONE?/results?
    # Test running with time limit for processing
    - echo "Testing with time limit"
    - rm -rf munged
    - munge-fah-data --projects projects.csv --outpath munged --maxits 2 --time 10 --sleeptime 0
    # Corrupt a file
    - echo "Corrupting a file"
    - rm -f munged/11507/run1-clone1.h5; touch munged/11507/run1-clone1.h5
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1
    # TODO: Test to make sure expected output is found
    - ls -ltr munged/11507
    - ls -ltr munged/11431
    - rm -rf munged
    # Remove unpacked files
    - rm -rf PROJ11507/RUN?/CLONE?/results?
    - rm -rf PROJ11419/RUN?/CLONE?/results?
    # Test serial debug mode
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --debug
    # TODO: Test to make sure expected output is found
    - ls -ltr munged/11507
    - ls -ltr munged/11431
    - rm -rf munged
    # Remove unpacked files
    - rm -rf PROJ11507/RUN?/CLONE?/results?
    - rm -rf PROJ11419/RUN?/CLONE?/results?
    # Test parallel with permanent deletion
    - echo "Testing irreversible unpacking with deletion of unpacked XML files"
    - munge-fah-data --projects projects.csv --outpath munged --maxits 1 --nprocesses 2 --xml delete --delete-tarballs

about:
  home: https://github.com/choderalab/fahmunge
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
